# .github/workflows/test.yml
name: GameRater CI

on: [workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      # Install your project packages & dependencies here
      # [..]

      # Install Testmo CLI tool locally (then use npx testmo .. to run it)
      - run: npm install --no-save @testmo/testmo-cli

      # Optionally add a couple of fields such as the git hash and link to the build
      - run: |
          npx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          npx testmo automation:resources:add-link --name build \
            --url $RUN_URL --resources resources.json

      # Run automated tests and report results to Testmo
      - run: |
          npx testmo automation:run:submit \
            --instance "$https://gamerater.testmo.net/" \
            --project-id 1 \
            --name "Test run" \
            --source "frontend" \
            --resources resources.json \
            --results results/*.xml \
            -- <your-test-command> # Run your automation tool; note space after --
        env:
          TESTMO_URL: ${{ https://gamerater.testmo.net/ }}
          TESTMO_TOKEN: ${{ JpdiI6ImU4UWxTOGxrYTAzVXNramdJLzk2dXc9PSIsInZhbHVlIjoiSll3S3pYTCthZEl1VTdibXkvRTZIYW5DVVk2TzhaakVnbUg0ay84U0E3WT0iLCJtYWMiOiJhNjJjYTQzNDVkYjU0ZjFlZDhhZDkwM2VkY2ZlOWYyOTM4OWUxOTUwZWQ2ZDQ4Mjk5NWVjNzBhYjQ5MDllMzgxIiwidGFnIjoiIn0 }}
