# .github/workflows/test.yml
name: GameRater CI

on: [workflow_dispatch]

defaults:
  run:
    working-directory: ./gamerater

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: npm

      # Install your project packages & dependencies here
      - run: |
          npm install
          npm build
      
      # Install Testmo CLI tool locally (then use npx testmo .. to run it)
      - run: npm install --no-save @testmo/testmo-cli

      # Run automated tests and report results to Testmo
      - run: |
          npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Test run" \
            --source "frontend" \
            --resources resources.json \
            --results results/*.xml \
            -- npm test
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
